### ISSUE TITLE
Optimized dataset size is > 2x larger than the original dataset size.

### ISSUE THREAD

**Issue by hiyyg** [Lightning-AI/litdata#261] opened 2024-07-23 08:30 UTC
Is this normal? How could we compress the dataset during dataset optimization or at least keep the original size?

**Comment by hiyyg** [comment] 2024-07-23 08:35
Any idea?

**Comment by hiyyg** [comment] 2024-07-23 09:00
When I use `compression="zstd"`, the size is still larger than the original size (e.g., 2.9G --> 3.5G).

**Comment by tchaton** [comment] 2024-07-23 10:12
Hey @hiyyg, Can you provide more information on what you are doing, otherwise those kind of issues aren't helpful for anyone.

Can you provide code sample to reproduce the issue, the index.json file associated to the chunks.

Most likely, you are storing the data into an un-optimized format leading to the data taking more space.

Example: 
- Storing image tensor vs JPEG is 10-100x bigger
- Storing video tensor vs av1 is 1000-5000x bigger

**Comment by hiyyg** [comment] 2024-07-23 11:24
Because uint16 depth data can not be saved in JPEG format, I directly save the original data using numpy arrays. I suppose that the optimized data should not be much larger than the original data. However, it is not as expected. So could you elaborate what litdata adds to the original data that makes it much larger?

**Comment by tchaton** [comment] 2024-07-23 12:38
Hey @hiyyg. Can you share a reproducible code snippet with synthetic data ? Alternatively, you can convert you data to bytes directly, so LitData doesn't try anything clever and you retain full control.

**Comment by tchaton** [comment] 2024-07-23 14:33
Hey @hiyyg Can you share a reproducible code snippet with synthetic data ? I can't help you otherwise.

**Comment by AugustDev** [comment] 2024-08-04 10:28
When I was using no compression the 54MB data file was saved as 1.6GB! Introducing `compression="zstd"` reduced the size to 16MB. However, compression seems to be undocumented feature. Could you please document and share recommendations?

**Comment by tchaton** [comment] 2024-08-04 13:26
Hey @AugustDev. Do you want to make a PR and update the README to add compression support ?

**Comment by tchaton** [comment] 2024-08-05 09:37
Hey @AugustDev. I updated the README to include compression. Let me know if I can close this issue.

**Closed** 2024-08-06 21:42 UTC
Labels: bug, help wanted
